# directories and model files
image_dir:  "/path/to/image_dir"
working_dir: "/path/to/working_dir"
detector_file: "/path/to/detector.ext"
classifier_file: "/path/to/classifier.ext"
class_list: "/path/to/classlist.csv"
# link_dir: "/path/to/image_dir" without this key, will save to working_dir/Sorted

# file metadata
exif: True
station_dir: -1 

# video processing
parallel: True
frames: 1
fps: None

# inference
device: cuda:0
checkpoint_frequency: 1000
batch_size: 4
num_workers: 4
file_col_detection: frame
file_col_classification: frame
class_label_col: class

# sort
sort: False
copy: False