# input
manifest: "/path/to/manifest.csv"
file_col: 'frame'
split_animals: True  # only run inference on MD category=1 (animals)

# model
classifier_file: "/path/to/classifier.ext"
class_list: "/path/to/classifier_labels.csv"

# output
out_file: None
raw: False

# model options
crop: True
resize_width: 480
resize_height: 480
normalize: True

# dataloader
batch_size: 1 
num_workers: 1